name: Terraform Deployment

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1

jobs:
  # ----------------------------------------------------------
  # STEP 1: Create Backend (S3 + DynamoDB) - Run once
  # This is only require to be run once to setup the backend
  # ----------------------------------------------------------
#  backend:
#    name: Setup Terraform Backend
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./terraform/backend
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.AWS_REGION }}
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v3
#        with:
#          terraform_version: 1.7.4    
#
#      - name: Clean Terraform cache
#        run: |
#          rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup
#
#      - name: Initialize Terraform
#        run: terraform init -reconfigure -upgrade
#
#      - name: Validate Terraform configuration
#        run: terraform validate
#
#      - name: Plan Terraform backend
#        run: terraform plan -out=tfplan -var="bucket_name=ddac-tf-state-backend"
#
#      - name: Apply Terraform backend
#        run: terraform apply -auto-approve tfplan

# ----------------------------------------------------------
# STEP 2: Deploy Infrastructure (VPC, EC2, etc.)
# ----------------------------------------------------------
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4            

      - name: Clean Terraform cache
        run: |
          # Removed .terraform.lock.hcl from deletion to ensure consistent provider versions
          rm -rf .terraform terraform.tfstate terraform.tfstate.backup

      - name: Terraform Format - Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Format
        run: terraform fmt -recursive  

      - name: Terraform Initial - Initialize (uses backend)
        run: terraform init -reconfigure -upgrade

      - name: Terraform Validate - Validate configuration
        run: terraform validate

      - name: Terraform Plan - Plan deployment
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
          TF_VAR_domain_name: "residentpro.click"
        run: terraform plan -out=tfplan

      - name: Terraform Apply - Apply changes
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
          TF_VAR_domain_name: "residentpro.click"
        run: terraform apply -auto-approve tfplan
